---
- hosts: all
  become: yes
  tasks:

  - name: Set a hostname
    ansible.builtin.hostname:
      name: monitoring

  - name: Set timezone to Europe/Kiev
    timezone:
      name: Europe/Kiev

  - name: Creates directory
    ansible.builtin.file:
      path: /data
      state: directory
      mode: '777'
      recurse: yes

  - name: Install Prometheus
    include_role:
      name: cloudalchemy.prometheus
    vars:
      prometheus_version: 2.25.0
      prometheus_web_listen_address: 0.0.0.0:9098
      prometheus_db_dir: /data
      prometheus_targets:
        node:
        - targets:
          - 192.168.50.2:9100

  - name: Install Node Exporter
    include_role:
      name: cloudalchemy.node-exporter

  - name: Install nessesary package
    apt: 
        name: apt-transport-https
        state: present
        update_cache: yes

  - name: add grafana gpg key
    shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

  - name: add grafana repo 
    apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      filename: grafana

  - name: Install grafana
    apt: 
        name: grafana
        state: present
        update_cache: yes

  - name: Enable and start grafana service
    service:
      name: grafana-server
      enabled: yes
      state: started


 # - name: Set Datasource
 #   grafana_datasources:
 #   - name: prometheus
 #     type: prometheus
 #     url: 'http://192.168.50.2'
 #     basicAuth: false

  - name: Change Grafana User
    community.grafana.grafana_user:
     url: "http://192.168.50.2:3000"
     url_username: admin
     url_password: admin
     name: "Bruce Wayne"
     email: batman@gotham.city
     login: batman
     password: robin
     is_admin: true
     state: present

  - name: Delete a Grafana user
    community.grafana.grafana_user:
     url: "http://192.168.50.2:3000"
     url_username: batman
     url_password: robin
     login: admin
     state: absent