---
- hosts: all
  become: yes
  tasks:

  - name: Set a hostname
    ansible.builtin.hostname:
      name: monitoring

  - name: Set timezone to Europe/Kiev
    timezone:
      name: Europe/Kiev

  - name: Creates directory
    ansible.builtin.file:
      path: /data
      state: directory
      mode: '777'
      recurse: yes

  - name: Install Prometheus
    include_role:
      name: cloudalchemy.prometheus
    vars:
      prometheus_version: 2.25.0
      prometheus_web_listen_address: 0.0.0.0:9098
      prometheus_db_dir: /data
      prometheus_targets:
        node:
        - targets:
          - 192.168.50.2:9100

  - name: Install Node Exporter
    include_role:
      name: cloudalchemy.node-exporter

  - name: Grafana
    include_role:
      name: cloudalchemy.grafana
    vars:
      grafana_security:
        admin_user: admin
        admin_password: "password"
      grafana_datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: 'http://0.0.0.0:9098'
          basicAuth: false

  - name: Change Grafana User
    community.grafana.grafana_user:
      url: "http://192.168.50.2:3000"
      url_username: admin
      url_password: password
      name: "Bruce Wayne"
      email: batman@gotham.city
      login: batman
      password: robin
      is_admin: true
      state: present
